# Site settings
title: Solace REST Messaging API
summary: These tutorials get you up to speed sending and receiving messages with Solace technology.
baseurl: "/solace-samples-rest-messaging" # the subpath of your site, e.g. /solace-samples-java
repository: https://github.com/SolaceSamples/solace-samples-rest-messaging

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Links
docs-core-concepts: http://docs.solace.com/Features/Core-Concepts.htm
docs-topic-matching: http://docs.solace.com/Features/Topic-Matching-and-Delivery-Modes.htm
docs-vmr-defaults: http://docs.solace.com/Solace-VMR-Set-Up/VMR-Configuration-Defaults.htm
docs-rest-messaging: http://docs.solace.com/Open-APIs-Protocols/REST-home.htm
docs-rest-introduction: http://docs.solace.com/Features/Using-REST.htm
docs-rest-concepts: http://docs.solace.com/Features/REST-Messaging-Concepts/REST-Msging-Concepts.htm
docs-rest-protocol: http://docs.solace.com/RESTMessagingPrtl/Solace-REST-Overview.htm
docs-vmr-setup: http://docs.solace.com/Solace-VMR-Set-Up/Setting-Up-VMRs.htm
links-community: http://dev.solace.com/community/


#----------------------------------------------------
# Generally don't modify items below this point
url: "solacesamples.github.io" # the base hostname & protocol for your site

# Google services
google_analytics: UA-3921398-7

# Build settings
markdown: kramdown

collections:
  tutorials:
    output: true
    permalink: /:path/
